-- 002_bookings_constraints.sql
-- Address audit findings:
--   H3 — reminders.js is not idempotent. Same booking can get the same reminder
--        twice if the cron's ±15 min window overlaps. Fix: per-stage timestamps.
--   H11 — bookings.datetime needs UNIQUE so api/book.js double-booking 409 path
--         is enforced by the database, not just by application logic.
--
-- Run order: after 001_agent_logging.sql.
-- Forward-only — do not edit this file once committed; add a new migration to amend.

-- 1) Enforce one booking per slot. If duplicates already exist this will fail; clean
-- them up first by inspecting `select datetime, count(*) from bookings group by 1 having count(*) > 1`.
ALTER TABLE bookings
  ADD CONSTRAINT bookings_datetime_unique UNIQUE (datetime);

-- 2) Per-stage reminder timestamps. NULL = not yet sent. Set when the cron sends
-- the corresponding reminder; check before sending to skip duplicates.
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS reminded_24h_at  timestamptz,
  ADD COLUMN IF NOT EXISTS reminded_1h_at   timestamptz;

-- Optional: speed up the cron query that filters bookings by datetime AND reminder state.
CREATE INDEX IF NOT EXISTS bookings_datetime_idx          ON bookings (datetime);
CREATE INDEX IF NOT EXISTS bookings_reminded_24h_at_idx   ON bookings (reminded_24h_at);
CREATE INDEX IF NOT EXISTS bookings_reminded_1h_at_idx    ON bookings (reminded_1h_at);
